# Write your MySQL query statement below
SELECT LEFT(TRANS_DATE,7) AS MONTH ,
COUNTRY ,
COUNT(ID) AS TRANS_COUNT , 
SUM(IF(STATE='APPROVED',1,0)) AS APPROVED_COUNT,
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT ,
SUM(IF(STATE='APPROVED',AMOUNT,0)) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY COUNTRY, LEFT(TRANS_DATE,7)
