# Write your MySQL query statement below
SELECT P.PRODUCT_ID , IFNULL(ROUND(SUM(US.UNITS*P.PRICE)/SUM(US.UNITS),2),0) AS AVERAGE_PRICE
FROM PRICES AS P
LEFT JOIN UNITSSOLD AS US
ON P.PRODUCT_ID = US.PRODUCT_ID
AND US.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID

